server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: cos
    password: cos1234
    url: jdbc:mariadb://localhost:3306/greendb?serverTimezone=Asia/Seoul
    
  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
